### ISSUE TITLE
Error: COFF  libraries not supported

### ISSUE THREAD

**Issue by bymihaj** [anton-dutov/mail#4]
Hello
I just try to create empty project with "mail", but building failed

os ver
Microsoft Windows [Version 6.1.7601]

dmd --version
DMD32 D Compiler v2.071.2

dub --version
DUB version 1.0.0, built on Jun 20 2016

dub run
Performing "debug" build using dmd for x86.
mail 0.2.1: building configuration "library"...
C:\Users\mihaj\AppData\Roaming\dub\packages\openssl-1.1.4_1.0.1g\openssl\deimos\
openssl\bio.d(81,9): Deprecation: module std.c.windows.winsock is deprecated - I
mport core.sys.windows.winsock2 instead
C:\Users\mihaj\AppData\Roaming\dub\packages\openssl-1.1.4_1.0.1g\openssl\deimos\
openssl\dtls1.d(76,8): Deprecation: module std.c.windows.winsock is deprecated -
 Import core.sys.windows.winsock2 instead
C:\Users\mihaj\AppData\Roaming\dub\packages\mail-0.2.1\mail.dub\build\library-d
ebug-windows-x86-dmd_2071-CF51EAD151C814510F6703F33F95ED2F\mail.lib: Error: COFF
 libraries not supported
C:\Users\mihaj\AppData\Roaming\dub\packages\mail-0.2.1\mail.dub\build\library-d
ebug-windows-x86-dmd_2071-CF51EAD151C814510F6703F33F95ED2F\mail.lib: Error: COFF
 libraries not supported
C:\Users\mihaj\AppData\Roaming\dub\packages\mail-0.2.1\mail.dub\build\library-d
ebug-windows-x86-dmd_2071-CF51EAD151C814510F6703F33F95ED2F\mail.lib: Error: COFF
 libraries not supported
dmd failed with exit code 1.

**Comment by anton-dutov** [comment]
I'll try build on windows today (i use linux anywhere), if you known any good solution, don't shy, tell me =)
